language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: kNuHd9BkeDGWzhsuDhrpI10Z4WD/+SIwJorFEEVy7QbxVCXBdtmxRfO49vd2c8+HEIO0NRORqHLfmVRkANvV0y2OYKxSh+XpiDH2odYZ010xsyohv/vGFeqOp6WPBRwCQgzfg51/KGGpHDNEMwv6KGtVWVefgTv2L/HqgvIzC/f24zKzUngxqn6X9DDH9lYdsLCmTUN6YRnG0twITxrRvPebRwjdL7nO69OT2BZEU7XNgx6jBQyB435hnWEPrP4TNLB3E/IgUa0pi6TfysVu5nbtL/e8FepBzonCrmy1KTXFamPM/KdxfdQKtNjDwV9kv1tI+I9BPHSzzlxRliH5iTJ83P3IKqiP2XciMJCTSITuYvvju8ShtKj14+EmYRwH3ZguU/zPCovyF5D4tEwqRf+a+g/UfZe+ramg/394slwOj6nXG/DRgq4WnNjdExAZe6fjCU1dK8hKQZe8b+N/x84toY96AC2sOFfXYxJW5MGJ2HPvAhqWVaT4Zz8OCPMzuiWUoeqJXfH6fP9tHfRMTF7Ku2fb4yQ49KNFv5WpI+v4Nnwo2XnGFkomVNk4RdMbaeBjTsOO7inFJ3kvNo8eslNnAQ2RroKveA30CadbTke6x0zvVhnyyZ6N8RRtEwP27SNTPraGwyWO6tyV+y1hA4ainR3TUNHqKEB4gBzpvx0=
  app: mighty-waters-71819
  on:
    repo: aaronleebrooks/blogPosts
